# Select the proper tag: refer to https://github.com/SergioGasquez/esp-rs-container
# for more information about tags
image:
  file: .gitpod.Dockerfile
tasks:
 - name: Setup environment variables for Rust and ESP-IDF
   command: |
     source /home/gitpod/export-rust.sh
     export IDF_TOOLS_PATH=/home/gitpod/.espressif
     source /home/gitpod/.espressif/frameworks/esp-idf-v4.4/export.sh
     export CURRENT_PROJECT=/workspace/rustzx-esp32/

vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
ports:
  - port: 9012
    visibility: public
