

[wokwi]
version = 1
#elf = "target/riscv32imac-unknown-none-elf/debug/rustzx-esp32-c3-devkit-rust"
#firmware = "target/riscv32imac-unknown-none-elf/debug/rustzx-esp32-c3-devkit-rust"
gdbServerPort = 3333

elf = "target/riscv32imac-unknown-none-elf/release/rustzx-esp32-c3-devkit-rust"
firmware = "target/riscv32imac-unknown-none-elf/release/rustzx-esp32-c3-devkit-rust"
